id: cacd011d4286486ea816a3ba088ad56f
initial_creation_type: ebook
source_metadata:
  title: test 1000
  subtitle: test
  authors:
  - test
  collection: test
  publisher: test
  id: SKU-01
  cover: tmpu0nizk1r.jpg
  credit: tmpy1g09mjr.jpg
